export enum ERights {
  INVITED = "INVITED",
  PRIVILEGED = "PRIVILEGED",
}

export enum ERightsAdmin {
  ADMIN = "ADMIN",
  EDITOR = "EDITOR",
  USER = "USER",
}

export enum EDBNameTable {
  USERS_TABLE = "USERS_TABLE",
  USER_CONF_TABLE = "USER_CONF_TABLE",
  GROUPS_TABLE = "GROUPS_TABLE",
  GROUP_CONF_TABLE = "GROUP_CONF_TABLE",
  RIGHTS_USERS_TABLE = "RIGHTS_USERS_TABLE",
  RIGHTS_GROUPS_TABLE = "RIGHTS_GROUPS_TABLE",
  CONFORMITIES_TABLE = "CONFORMITIES_TABLE",
  TASKS_TABLE = "TASKS_TABLE",
  TASK_CATEGORY_TABLE = "TASKS_CATEGORY_TABLE",
  QUESTIONNAIRE = "QUESTIONNAIRE"
}
