export const UPDATE_TIME = "UPDATE_TIME";
export const UPDATE_END_DATE = "START_DATE";
export const UPDATE_COUNTER_ANSWERS = "UPDATE_COUNTER_ANSWERS";
export const UPDATE_COUNTER_QUESTIONS = "UPDATE_COUNTER_QUESTIONS";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const UPDATE_ID = "UPDATE_ID";
export const FINISH = "FINISH";
